### ISSUE TITLE
Not sure if bug or intended

### ISSUE THREAD

**Issue by Miner94** [Edivad99/ExtraStorage#10]
I learned last night that if you pick up any of the extra storage crafters with the carry on mod it will delete all the patters inside the crafter

**Comment by bloodscon** [comment]
Dam I'm shocked  it only deleted the patterns as your moving an item that has nbt data on it plus the patterns will have nbt data on them

**Comment by Edivad99** [comment]
Does the refined storage crafter have the same bug?

**Comment by Miner94** [comment]
not sure let me check

**Comment by Edivad99** [comment]
If the RS adds this option, reopen the issue
