### ISSUE TITLE
recipes in the diamond crafter getting deleted after restart of the game

### ISSUE THREAD

**Issue by FennixJP** [Edivad99/ExtraStorage#11]
**Describe the bug**
I setup a 64k storage disk recipe yesterday and was using it to craft said 64k disks.
I saved the game and restarted it now all the recipes are gone.
All the speed upgrades are gone as well.
**Configuration**
Mod version:1.2.1
Forge version:35.1.4
Minecraft version:1.16.4
Refined Storage version:1.9.9
Are you playing on server?:no

**To Reproduce**
1,save the game
2,restart the game

**Expected behavior**
all the recipes in the crafter getting deleted

**Screenshots**
![Screenshot (605)](https://user-images.githubusercontent.com/66977477/101602541-a1657c00-3a41-11eb-8ac8-88b5066ae26c.png)
![Screenshot (606)](https://user-images.githubusercontent.com/66977477/101602557-a6c2c680-3a41-11eb-9f79-077c87d8c161.png)

**Additional context**

**Comment by Edivad99** [comment]
I can't reproduce your problem

**Comment by FennixJP** [comment]
It might've been a random bug that happened i have no idea
