### ISSUE TITLE
[Suggestion] Mekanism Gas Compatibility

### ISSUE THREAD

**Issue by NillerMedDild** [Edivad99/ExtraStorage#15]
Hey there o/

It'd be really nice to be able to store Mekanism Gas inside our Refined Storage systems, like we can with fluid. 
Would you perhaps look into adding that, or is it outside the scope of this mod? :)

**Comment by Ridanisaurus** [comment]
I would also be more than happy to supply the textures for it, if needed.

**Comment by Edivad99** [comment]
It is quite difficult to add gas compatibility from Mekanism, perhaps you need to make this request to the creators of Refined Storage.

**Comment by NillerMedDild** [comment]
Alright, thanks for considering it :)
