### ISSUE TITLE
[Extra Storage] A new version is available (null), please update!

### ISSUE THREAD

**Issue by Brittank88** [Edivad99/ExtraStorage#19]
**Describe the bug**
Despite using the current latest version of Extra Storage (1.3.1), I am warned that I should update to a version that.. uh.. doesn't exist?

**Configuration**
Mod version: `1.16.4-1.3.1`
Forge version: `36.0.9`
Minecraft version: `1.16.5`
Refined Storage version: `1.9.11`
Are you playing on a server? **No.**

**To Reproduce**
Steps to reproduce the behaviour:
1. Install latest Extra Storage + any dependencies.
2. Enter a world.
3. Be asked to time travel to the future to install an update of the mod that doesn't exist yet.

**Expected behaviour**
Not being warned when I don't need to be would suffice.

**Screenshots**
![image](https://user-images.githubusercontent.com/24266948/106260350-70047200-6274-11eb-8334-8e1f1a2266d5.png)

**Comment by Edivad99** [comment]
It should be fixed now.

**Comment by Brittank88** [comment]
Awesome, thank you!
