### ISSUE TITLE
1.16.5 Export profille

### ISSUE THREAD

**Issue by Mini-kun** [Edivad99/ExtraStorage#20]
**Describe the bug**
it's not allowing me to export it to Cureseforge i have and i need op

**Configuration**
Mod version: 1.3.1
Forge version: 36.0.14
Minecraft version: 1.16.5
Refined Storage version:  1.9.11
Are you playing on server?: Well Yes

**To Reproduce**
This is on Curseforge Export settings

**Expected behavior**
Curseforge mods are Deny me uploading it

**Screenshots**
I have none

**Additional context**
None

**Comment by Edivad99** [comment]
From what you say it looks like a problem with the curseforge app, not mine
