### ISSUE TITLE
Advanced Importer buttons

### ISSUE THREAD

**Issue by Rithenar** [Edivad99/ExtraStorage#21]
**Describe the bug**
When trying to set black list, exact mode, items/fluids, the buttons to the left do not work. You can click them, but they won't change. Also when clicking on the Items/Fluids button, it enables redstone.

**Configuration**
Mod version: 1.3.1
Forge version: 36.0.13
Minecraft version: 1.16.5
Refined Storage version: 1.9.11
Are you playing on server?: Yes

**To Reproduce**
1. Craft and Advanced Importer and place it
2. Click on options buttons on left
3. Seer nothing happen

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Edivad99** [comment]
Tested on minecraft 1.16.4 and everything works

**Comment by Rithenar** [comment]
This is in 1.16.5 as stated above. Will the importer not work properly in 1.16.5 but the rest of items will?

**Comment by Edivad99** [comment]
Things that work in 1.16.4 also work in 1.16.5. Your problem is strange, I am waiting for other reports from other users

**Comment by Rithenar** [comment]
Understood. Thank you.

**Comment by Zeentch** [comment]
I'm on 1.16.5 and i have no issues at all with the Importer/Exporter buttons, they work as i expected. You might want to check if there is any other mod that is causing this issue.
