### ISSUE TITLE
Suggestion: Crafter(s) with Input Slots

### ISSUE THREAD

**Issue by TemperedFool** [Edivad99/ExtraStorage#23]
I'm also going to suggest this to the base mod, but it would be nice if your crafters had functionality similar to an interface (like AE2 interfaces) - allow it to accept inputted items and store them, and as a bonus allow them to supply materials (with autocrafting via crafting cards).

This is super nice when a machine is capable of auto-outputting out of a side - it means you don't need an importer on the machine. Bonus if it can accept fluids too!

The item supply is nice for things like Mekanism Enrichment Chambers, that need a steady supply of an infusing material.

**Comment by cdelog** [comment]
Not sure if this is going to receive attention, but on the chance that it does, AE2 interfaces observe a bug that you could avoid in your RS Crafter if you do this right. When you deposit items into an AE2 interface from a machine, those slots are valid output slots and so if the machine is running fast (say tick acceleration) it can output an item to the interface then pull it back out before the interface has time to insert the item into the network. The solution for this would be to make the crafter output slots only accessible as output and input slots ONLY accessible as input.
