### ISSUE TITLE
Tiered Crafters movable by Pistons.

### ISSUE THREAD

**Issue by bfc19** [Edivad99/ExtraStorage#25]
**Describe the bug**
Patterns are lost when the Netherite Crafter is moved with Redstone via a sticky piston. It should not be able to be moved with a piston as base behavior of the Crafter from Refined Storage is unmovable by pistons.

**Configuration**
Mod version: 1.16.4-1.3.1
Forge version: 36.1.2
Minecraft version: 1.16.5
Refined Storage version:
Are you playing on server?: Yes

**To Reproduce**
1. Get Piston and Netherite Crafter
2. Power Piston and move Crafter
3. All patterns lost

**Expected behavior**
Expected to just work, with all patterns intact.

**Additional context**
Make Tiered Crafters unmovable by pistons, similar to how the refined storage ones are.

**Comment by Edivad99** [comment]
I can't reproduce your problem!
Mod version: 1.16.4-1.3.1
Forge version: 36.14
Minecraft version: 1.16.5
![image](https://user-images.githubusercontent.com/25778604/115118535-f7c06980-9fa3-11eb-9254-7584858ef62c.png)
