### ISSUE TITLE
Newest version breaks vanilla double chests, can't open gui. Rolling back version fixes it.

### ISSUE THREAD

**Issue by snarkbait66** [Edivad99/ExtraStorage#30]
**Describe the bug**

**Configuration**
Mod version:
Forge version:
Minecraft version:
Refined Storage version:
Are you playing on server?:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Edivad99** [comment]
Explain a little better.... It works for me to open a double chest

**Comment by snarkbait66** [comment]
Updated mod, updated it on server and client. Ran client, single chests open and show gui. Double chests show open animation, but do not show gui. This is on a custom modpack forge 35.1 about 170 mods. Rolling back to prior version corrected the problem.

**Comment by Edivad99** [comment]
![image](https://user-images.githubusercontent.com/25778604/120082189-d766ed00-c0c1-11eb-996b-97e5cca9144f.png)

**Comment by Edivad99** [comment]
It works for me

**Comment by snarkbait66** [comment]
try a double chest with something on top of it, like another chest or botany pots, all of the chests I had were stacked

**Comment by Edivad99** [comment]
It works the same, I think you have problems with another mod. I didn't touch anything related to the chests
