### ISSUE TITLE
AI Issue

### ISSUE THREAD

**Issue by bblaze1001** [Edivad99/ExtraStorage#32]
**Describe the bug**
I was asked to put this here :D I have an AI Issue on the latest steps of building Oak 3 playerhousing of minecolonies. Here is the Gist https://gist.github.com/Flami21/d29fb525c0979ec3b2d4a7c14fb9287d

**Configuration**
Mod version: 0.14.221-BETA
Forge version: 36.1.31
Minecraft version: 1.16.5
Refined Storage version: 1.9.12
Are you playing on server?: yes

**To Reproduce**
1. Use the building tool
2. Click on 'player housing' and select Oak
3. Upgrade it all the way to Oak 3
4. All colonists working on it have this issue

**Expected behavior**
To finish building the structure without errors.

**Screenshots**
![AI Issue](https://user-images.githubusercontent.com/85800597/122948286-2fa3ae80-d351-11eb-820b-90a68050a42c.png)
After contacting Minecolonies github, they told me to post it here so I gladly will.

**Additional context**

**Comment by Edivad99** [comment]
I don't know the Minecolonies, could you do me a favor? Check if the same problem occurs with the RefinedStorage base crafter

**Comment by bblaze1001** [comment]
nope, it does not. I used the Iron Crafter multiple times without an issue

**Comment by ravenbuilder934** [comment]
here's the mcol issue as a note https://github.com/ldtteam/minecolonies/issues/7282

**Comment by bblaze1001** [comment]
yes, I made that issue (I was logged on my other account). On the comments, you can see they redirect me here :p

**Comment by ravenbuilder934** [comment]
yeah I know, wanted to crosslink it in case Edivad wanted to see it :smile:

**Comment by bblaze1001** [comment]
Ohhh, I didn't see it wasn't Edivad who crosslinked haha sorry
