### ISSUE TITLE
[Feature Request] Upgraded Disk Manipulators

### ISSUE THREAD

**Issue by C4J3** [Edivad99/ExtraStorage#33]
So I recently started playing with this mod in my custom pack after discovering Reborn Storage hasn't been ported to 1.16 and honestly I think I prefer this solution. I was wondering if you think it would be possible to add a similar tiered upgrade system for Disk Manipulators as well? Every other RS mod adds larger disks at this point but moving items from them is incredibly slow at the even with max upgrades but I think this idea would be an awesome fix!

**Comment by starforcraft** [comment]
Actually Cable Tiers has recently added Tiered ones

**Comment by yavuzselim313** [comment]
A mod called "Cable Tiers" added them recently
