### ISSUE TITLE
Netherite Crafter losing patterns while logged in

### ISSUE THREAD

**Issue by WorldTeacher** [Edivad99/ExtraStorage#34]
**Describe the bug**
The Netherite crafter looses all the Patterns stored in it. I've even had this happen while a crafting process was in progress. 

**Configuration** (will add this later on, as I'm currently on mobile and not on my Pc) 
Mod version:
Forge version:
Minecraft version:
Refined Storage version:
Are you playing on server?:
Yes
Modpack: Enigmatica 6, v0.5.10
**To Reproduce**
1. Fill up almost all patterns in the netherite crafter
2. Start a process
3. Wait

**Expected behavior**
The patterns should persist in the crafter, even if they are not used. 

**Screenshots**
None

**Comment by Edivad99** [comment]
I have yet to fully investigate the problem, but the other day I saw a similar problem for the Refines Storage as well refinedmods/refinedstorage#2922

**Comment by Edivad99** [comment]
I cannot reproduce this problem with an installation containing only:
- Refined Storage 1.9.15
- Extra Storage 1.4.1

There will likely be a conflict with a mod

**Comment by NillerMedDild** [comment]
Do you have any ideas as to what could be interfering?

**Comment by bobbysock** [comment]
Just for reference, I experienced something similar in the FTB OceanBlock modpack, where the patterns was either deleted or swapped around mixing processing and normal patterns in different crafters. I suspected that it was a bug in the Crafter Manager, but I'm not sure.

**Comment by Edivad99** [comment]
Check #44
