### ISSUE TITLE
Iron Crafter sometimes not named correctly

### ISSUE THREAD

**Issue by bulldog98** [Edivad99/ExtraStorage#39]
**Describe the bug**
If you place a new Iron Crafter, sometimes it is named (in it's GUI) after the last opened Block from Refined Storage

**Configuration**
Mod version: 1.5.0
Forge version: 26.2.9, also seen in 26.2.8
Minecraft version: 1.16.5
Refined Storage version: 1.9.15
Are you playing on server?: no

**To Reproduce**
1. In a new world place a creative controller
2. Open the GUI of the creative controller
3. Place an Iron Crafter
4. Open it with a right click
5. See error

**Expected behavior**
The title in the GUI should say Iron Crafter

**Screenshots**
![Extra Storage Bug](https://user-images.githubusercontent.com/314259/140645058-e362c047-c3ea-46aa-8de5-f4be8d6a554e.png)

**Additional context**
Placing an other shows the right title in it's GUI.

**Comment by Edivad99** [comment]
It's correct because is pointing another block
