### ISSUE TITLE
[Suggestion] Ore Dictionary Exporter

### ISSUE THREAD

**Issue by XXxinsanityxX** [Edivad99/ExtraStorage#4]
An advanced version of an exporter that allows the RS system to push items into an inventory using wildcards.

Perhaps it can be like an upgrade where you put it in a normal exporter and it changes from having 9 slots into a typing bar.

Extra cells had sonething like it for 1.12.
https://m.ftbwiki.org/ME_Ore_Dictionary_Export_Bus#:~:text=The%20ME%20Ore%20Dictionary%20Export,Put%20%22ore*%22%5D.

**Comment by Edivad99** [comment]
I'm working on it, as you can see I have already created some classes. I want to understand how to make filter input simple

**Comment by sarim** [comment]
Was there any progress about this? For implementation maybe refined storage's filter can be used? You don't need to make gui for filtering that way. That filter can be inserted to a special Importer/Exporter. Maybe call them "Filtered Importer"/"Filtered Exporter"
