### ISSUE TITLE
Crafter not showing redstone icon

### ISSUE THREAD

**Issue by EnabledEnzo** [Edivad99/ExtraStorage#43]
**Describe the bug**
Crafters do not allow for redstone configuration.

**Configuration**
Mod version:1.5.1
Forge version:36.2.8
Minecraft version:1.16.5
Refined Storage version:1.9.16
Are you playing on server?:yes

**To Reproduce**
1. Go to an active crafter from the mod
2. 'the button for redstone  is not there'

**Expected behavior**
The redstone configuration icon to appear like refined storage's crafter.

**Screenshots**
https://imgur.com/a/egQ9jTc

**Additional context**

**Comment by Edivad99** [comment]
https://github.com/Edivad99/ExtraStorage/issues/29
