### ISSUE TITLE
Netherite crafter voids my pattern after i relog UP

### ISSUE THREAD

**Issue by player1560** [Edivad99/ExtraStorage#44]
**Describe the bug**
After playing for while, i reload my client and when i relog, the patterns inside my netherite crafter arent there anymore. first tought i was dumb, but next morning happenend again 

**Configuration**
Mod version: ExtraStorage-1.16.5-1.5.0.jar
Forge version: 36.2.8
Minecraft version: 1.16.5
Refined Storage version: refinedstorage-1.9.15.jar
Are you playing on server?: no

**To Reproduce**
1. Netherite Crafter with Pattern
2. Play for a while or let the game open for a while i guess
3.  Close and re-open the client by the intended way
3. relog and open your crafters 
4. no more patterns 

**Expected behavior**
you should notice that your patterns are gone for ever 

i don't think it's my setup of refined storage that's causing this but if needed i can provide a screenshot

**Comment by mariandaniel24** [comment]
Not to hijack this issue, but a similar thing happened to me as well, with some differences.
After we did a server restart, every pattern inside Diamond crafters simply vanished, the basic crafters from refined storage retained their patterns.

#### Configuration
Mod version: ExtraStorage-1.16.5-1.4.1.jar
Forge version: 36.2.2
Minecraft version: 1.16.5
Refined Storage version: refinedstorage-1.9.15.jar

This is on FTB Direwolf20 1.16.5 version 1.11.0.

Not sure if I can reproduce it right now, considering the server is public, I will have to wait until we do a server restart. I will edit this post with the result.

**Comment by player1560** [comment]
thank's for trying if you ask , i'm playing ragnamod VI

**Comment by ahmeij** [comment]
Similar thing seems to happen on our Oceanblock 1.9.0 server. All patterns in diamond crafters seem to have randomly moved to other diamond crafters, for the second time now. 

For example the patterns in the diamond crafter above the Mekanism enrichment factory are now placed in an other (not machine connected) diamond crafter.

Unclear if all patterns are retained or some are lost, still investigating.

No specific action seems to trigger this, or atleast I've not recognised the action preceding the events yet.

**Comment by mariandaniel24** [comment]
> 
> Not sure if I can reproduce it right now, considering the server is public, I will have to wait until we do a server restart. I will edit this post with the result.

Just restarted the server 2 days ago and I still have my patterns (now using netherite crafters), AFAIK no other player had this happening at all, so it seems to have been a one-time thing.

**Comment by Edivad99** [comment]
In the packs where you had these problems, did you have other addons for refined storage?

**Comment by ahmeij** [comment]
For Oceanblock 1.9.0 I see these other addons:
Refined Storage Addons (refinedstorageaddons-0.7.4.jar)
Refined Storage: Requestify (rsrequestify-1.16.5-2.1.4.jar)

I suspect the use of the Crafting manager being the problem, but this is a hunch atm. Will update with more detail if it happens again.

**Comment by Edivad99** [comment]
Honestly, I don't know what to say. I tried to insert the patterns inside the crafter via the crafter manager but I can't replicate your problem. As soon as that happens, you should send me the logs. I add that I followed a series on youtube/twitch where extra storage was used a lot and I have never seen similar problems.

**Comment by Felixchong882003** [comment]
I also got the same problem, i got the log of my server saying there is some error about the extra storage mode
[latest.log](https://github.com/Edivad99/ExtraStorage/files/7692879/latest.log)

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/454

this bug removed one crafter patterns in the last few day after I restart the server, hope this can help to fix the bug

**Comment by Felixchong882003** [comment]
Could this be related the mod that use mouse middle click to organize/sort inventory? It can move the speed upgrades into the pattern inventory and error will appear, may be when the server/player world reload, there is upgrade accidentally moved to the patterns space and the crash the crafter?
[another-error.log](https://github.com/Edivad99/ExtraStorage/files/7697394/another-error.log)

**Comment by Edivad99** [comment]
Unfortunately Quark doesn't allow me to automatically disable sort buttons in crafters. I saw that in the quark config file, there is an option to override the mod gui.
Then add in the quark-common file: `"Ignored Screens" = ["edivad.extrastorage.client.screen.AdvancedCrafterScreen"]`

**Comment by Edivad99** [comment]
OK, forget it. Unfortunately the APIs offered by the quark are quite poorly written, but I was able to disable the quark buttons from code. Next version will have this fix.
P.S. There is no need to modify the config file.
