### ISSUE TITLE
Server startup crash on latest forge

### ISSUE THREAD

**Issue by bigenergy** [Edivad99/ExtraStorage#47]
**Describe the bug**
the server does not start on the latest version of the forge

**Configuration**
Mod version: 1.6.0
Forge version: 36.2.22
Minecraft version: 1.16.5
Refined Storage version: 1.9.16
Are you playing on server?: yes

**To Reproduce**
1. Start server
2. Get crash

https://gist.github.com/bigenergy/6cdfb1d2840c576920c47fea494b2b70

**Comment by Edivad99** [comment]
Have you tried to go back the version of the extrastorage?

**Comment by Edivad99** [comment]
I talked to the developers of the RS, they told me that this can happen when a block is placed in a position, but there is already data for that position there. So usually when people rollback region files. It is possible to edit it out with nbt explorer
