### ISSUE TITLE
Issue on Server: Disappearing disks

### ISSUE THREAD

**Issue by MundM2007** [Edivad99/ExtraStorage#48]
**Describe the bug**
I'm a modpack Developer and I'm using Extra Storage with Extra Disks.
I'm running a server and since the new 1.6.0 version of Extra storage I'm encountering a wierd bug where the disks from extra disks disappeared (but for some reason this didn't happen all the time) when there is an automatic restart (using bisect hosting)
when i used version 1.5.1 this didn't happen.

**Configuration**
Mod version: 1.6.0
Forge version: 36.2.20
Minecraft version: 1.16.5
Refined Storage version: 1.9.16
Are you playing on server?: Yes

**To Reproduce**
1. Install both extra storage (v1.5.1) and extra disks (latest version) (or use the modpack) on a server
2. build an me(or multiple) and use disks form extra storage and extra disks, also put items into the me
3. stop the server and install extra disks v1.6.0
4. start the server and if there is an automatic restart happening there are disks removed

**Expected behavior**
Every thing stays the same and no disks disappear

**Additional context**
Modpack: Ultimate Progression v0.5.0 and y0.4.20

**Comment by Edivad99** [comment]
I have no idea. I haven't touched anything related to disks. The only thing I have done is fix the bugs of the patterns that disappeared when using the quark.
Remove the extradisk if it gives you trouble, as it adds the same content. 🤷‍♂️🤷‍♂️
