### ISSUE TITLE
[1.18.1] Exception in server tick loop | java.lang.NoClassDefFoundError: com/refinedmods/refinedstorage/util/WorldUtils

### ISSUE THREAD

**Issue by Gbergz** [Edivad99/ExtraStorage#50]
**Describe the bug**
Someone on our server placed an Advanced Importer then the server went into a crash loop. Won't start. Crashes once server is done loading.

**Configuration**
Mod version: 2.0.0
Forge version: 39.0.5
Minecraft version: 1.18.1
Refined Storage version: 1.10.0-beta.4
Are you playing on server?: Yes.

**To Reproduce**
1. Install Refined Storage 1.10.0-beta.4 & ExtraStorage 2.0.0
2. Place an Advanced Importer.
3. Server Crashes. Into crash loop.
4. Profit.

**Log parts**
1. https://gist.github.com/Gbergz/5f6cb1474a4982c158927f2f9375785f
2. https://gist.github.com/Gbergz/7312e5f7d3ae3689ed3a21bf922dfcf3

**Expected behavior**
That the server doesn't go into a crash loop once the Advanced Importer is placed.

**-** Gbergz

**Comment by Edivad99** [comment]
#49
