### ISSUE TITLE
(Suggestion) Add config and/or make use of RefinedStorage's config

### ISSUE THREAD

**Issue by NanobotZ** [Edivad99/ExtraStorage#54]
I think it would be nice to make this mod use the RefinedStorage configuration, or add it's own configuration.

My main issue is with crafter energy usage. I'm playing on a custom modpack where energy generation and transfer is very limited and it's impossible to power it well enough to make even 2 full diamond crafters work, even when powering the controller from all 5 sides.
I've tweaked the main RefinedStorage configs to make it more fair for players (as the power generation is fairly expensive), but this addon doesn't support any configuration and I have no clue what to do other than editing values in code and compiling the mod by myself (and then distributing the jar to players).

I'd greatly appreciate you adding configuration support.

**Comment by Edivad99** [comment]
I will consider your request. But distributing the mod outside of curseforge is no good!
