### ISSUE TITLE
Advanced crafter tiers do not uniformly distribute processing crafting requests over multiple stations

### ISSUE THREAD

**Issue by leviathan13** [Edivad99/ExtraStorage#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Set up an auto-smelting section (tested with 4 furnaces), if you use gold, diamond or netherite crafters on those stations, bulk crafting (smelting) requests will be all processed at once only by 1 crafter (2 with the gold tier), reducing efficiency of the whole set up. This does not work like Refined Storage's crafter which distribute the requests evenly. Iron tier can still distribute _almost_ evenly the requests, but I suppose it will have issues as well with higher numbers.

### How can I reproduce this bug or crash?

1. Set up a auto-smelting section with multiple furnaces and attached crafters (test different tiers separately).
2. Send a request to smelt multiple items (tested with orders between 10 and 64)
3. Observe how many furnaces are processing the request.

### Configuration

```markdown
- Mod version: ExtraStorage-1.18.1-2.0.1
- Refined Storage version: 1.10.0
- Forge version: 39.1.2
- Minecraft version: 1.18.1
```

### Anything else?

The mod's description page says that the advance crafter tiers have increased speed. If I have to guess, that's the reason why the top tiers ends up processing all the orders in a single station. I'm not sure if speed is relevant for processing recipes, so maybe crafters shouldn't use the "increased" speed for those kind of recipes or maybe the speed upgrades should be separated from the crafting station.

If the issue cannot be addressed, at least I would add a warning to the mod's description page.

**Comment by Edivad99** [comment]
Can you send me a picture of the setup you used?

**Comment by leviathan13** [comment]
[Here](https://imgur.com/a/xtZzOio) are some screenshots. I also attached the structure file of the set up. Unfortunately, I test loading the structure, but it didn't save any of the RS upgrades/disks (even with saved entities), so you will have to add the storage disk, set up the fuel, re-create the patterns and add them to every crafters.

[rs_extrastorage_debug.zip](https://github.com/Edivad99/ExtraStorage/files/8306858/rs_extrastorage_debug.zip)

**Comment by Edivad99** [comment]
Interesting, I will have a look
