### ISSUE TITLE
Speed upgrade duplication

### ISSUE THREAD

**Issue by koepss** [Edivad99/ExtraStorage#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When you scroll click in the netherite crafter's GUI with full upgrade speed it will duplicate them by 4.

### How can I reproduce this bug or crash?

https://user-images.githubusercontent.com/84397853/159995767-c15a9e51-8499-4dc3-b335-ffbcaedbaa5a.mp4

### Configuration

```markdown
- Mod version: 1.6.1
- Refined Storage version: 1.9.17
- Forge version: 36.2.30
- Minecraft version: 1.16.5
- simple inventory sorter version: 18.1.0
```

**Comment by Edivad99** [comment]
Can you give me the simple inventory sorter url on curseforge?

**Comment by koepss** [comment]
https://www.curseforge.com/minecraft/mc-mods/inventory-sorter

**Comment by Edivad99** [comment]
Ah ok, I was solving it 2 months ago, but unfortunately the APIs made available to the mod don't work. As soon as they are fixed I will fix them
