### ISSUE TITLE
[Suggestion] Tiered range upgrades/wireless transmitters

### ISSUE THREAD

**Issue by Andr0oS** [Edivad99/ExtraStorage#6]
Tiering up wireless transmitters to provide more range by default or a multiplier to range based on tier, or similarly tiered range upgrades to do the same function - both at the cost of extra power.

**Comment by Zeentch** [comment]
RSInfinityBooster exists for infinite wireless & dimensional upgrade, and yes they cost more power, just thought i'd let you know.
