### ISSUE TITLE
The Crafters doesn't put Fluid intro Machines 

### ISSUE THREAD

**Issue by Felix2144** [Edivad99/ExtraStorage#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

So i tried to Autocraft the Simpel Machine Frame from Industrial Foregoing
for that you need the Dissolution Chamber.
I first tried to do it with the Iron Crafter (I didn't tested it with the other Crafters from this mod), but it didnt put the Fluid in the machine but the Normal Crafter from RS dose.
It was no issue with the Crafting Pattern. 

### How can I reproduce this bug or crash?

Try to Autocraft a recipe with a fluid in it

### Configuration

```markdown
- Mod version: 3.0.1
- Refined Storage version: 1.11.1
- Forge version: 43.1.47
- Minecraft version: 1.19.2
```

**Comment by Edivad99** [comment]
I did some tests, and I'm unable to replicate your problem maybe you didn't configure well the Dissolution Chamber.

![Schermata del 2022-12-10 21-50-20](https://user-images.githubusercontent.com/25778604/206874757-985213b2-baba-4e11-a504-dc17fd621ecb.png)
![Schermata del 2022-12-10 21-50-30](https://user-images.githubusercontent.com/25778604/206874752-007033b7-472a-4a22-9d23-1e53091f37dc.png)
