### ISSUE TITLE
Crafters from this Mod have the Redstone Button Missing. Even with the Mods "Cable Tiers" and "Universal Grid" disabled.

### ISSUE THREAD

**Issue by marco3102** [Edivad99/ExtraStorage#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As the Title says. I know this issue has been noted a few times in this Github but the solution there was disabling the mods. which I did. Which fixed it at first, but then the issue returned. A restart fixed it. Now it doesnt.
In the Refined Storage Github it was said that it had to do with a desycn from a block relalated java command.

### How can I reproduce this bug or crash?

1. Play ATM8 on a Server
2. Get "lucky" and get a server/cöient desync.

### Configuration

```markdown
- Mod version: 3.0.1
- Refined Storage version: 1.11.6
- Forge version: 43.2.11
- Minecraft version: 1.19.2
```

**Comment by marco3102** [comment]
Could a lack of Ram be the cause of this issue? My server is running at near maximum

**Comment by Edivad99** [comment]
No, it's a known issue. The bug is from Refined Storage and its API. It was fixed with the new Refined Storage release for 1.20.1
