### ISSUE TITLE
Original crafters not working

### ISSUE THREAD

**Issue by lacomarca** [Edivad99/ExtraStorage#7]
**Describe the bug*
Since I added extra storage the original crafters from RS are not working. I need to use only yours: iron, golden, etc. As well, that would be amazing if recipe for your crafters could take colored crafters as well (only taking the normal original one). Could you please a look?

Thanks

**Configuration**
Mod version: ExtraStorage-1.16.3-1.1.0
Forge version: 34.1.19
Minecraft version: 1.16.3
Refined Storage version: refinedstorage-1.9.7
Are you playing on server?: yes

**To Reproduce**
1. I create a refined storage crafter, it's not working
2. I upgrade it to iron, golden, etc. and it works

**Expected behavior**
Refined Storage original ones working

**Comment by Edivad99** [comment]
With this configuration I did not find your bug:
Mod version: ExtraStorage-version on github(I will release the update now to make ExtraStorage compatible with the latest version of the Refined Storage)
Forge version: 34.1.25
Minecraft version: 1.16.3
Refined Storage version: refinedstorage-1.9.9
Are you playing on server ?: yes
