### ISSUE TITLE
Being able to put stack upgrades in the crafters

### ISSUE THREAD

**Issue by yutoe** [Edivad99/ExtraStorage#71]
### Is there an existing feature request for this?

- [x] I have searched the existing issues

### Describe the feature

Add the ability to add stack upgrades to the crafters, as when using modded furnaces the crafters cant keep up, and are the only thing slowing auto crafting processes. or at least make a config that allows it to be enabled

**Comment by Edivad99** [comment]
I don't think it is necessary with this commit (https://github.com/Edivad99/ExtraStorage/commit/409d7d8126708e0c141c6be6eb8fce313c1fe6b8) I leave the choice to the user.
