### ISSUE TITLE
Storage Parts and Disk are not showing up in JEI

### ISSUE THREAD

**Issue by Nicon4454** [Edivad99/ExtraStorage#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Just installed this to Direwolf 1.20 modpack and the storage parts and the disk are not showing up. there are recipes for the disk and storage parts. if you lookup the recipes for the storage blocks then lookup the uses for the storage parts the disk are there and have a recipe for them. 
 Mod Ver 1.20.1-4.0.4
MC Ver 1.20.1
neo forge 47.1.76
modernfix 5.9.3
Modpack ver 1.8.0

### How can I reproduce this bug or crash?

install on server of Direwolf20 1.20.1-1.8.0

### Configuration

```markdown
- Mod version:4.0.4
- Refined Storage version:1.12.4
- Forge version:47.1.76
- Minecraft version:1.20.1
```

**Comment by Nicon4454** [comment]
just checked the creative tab does not show up there either

**Comment by Edivad99** [comment]
Ops

**Comment by Nicon4454** [comment]
is there and eta on when a new release will be out to fix this issue?
