### ISSUE TITLE
unable to get covers to attach

### ISSUE THREAD

**Issue by Nicon4454** [Edivad99/ExtraStorage#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

i am unable to get covers to attach to the importer and exporter. i have had the importer eat the cover when trying to attach from the front of the importer

### How can I reproduce this bug or crash?

tray to attach a cover

### Configuration

```markdown
- Mod version:4.0.5
- Refined Storage version:1.12.4
- Forge version:47.1.76
- Minecraft version:1.20.1
```

### Relevant log output

```shell
none
```

**Comment by rcfox2** [comment]
This issue is happening for me again on 
Refined Storage 1.12.4
ExtraStorage 4.0.7
Forge Version 47.2.20
Minecraft Version: 1.20.1
